[package]
name = "lucis"
version = "0.1.0"
authors = ["Shaun Bennett <me@phinary.ca>"]

[dependencies]
image = "0.20.1"
png = "0.13.1"
nalgebra = "0.16.10"
rand = "0.6.0"
rlua = "0.15.3"
roots = "0.0.4"
rayon = "1.0.3"
